name: Build Harbor ARM64

on:
  workflow_dispatch:
    inputs:
      harbor_version:
        description: Harbor version tag
        required: true
        default: v2.9.0
      registry:
        description: Registry server (e.g., ghcr.io or registry.example.com)
        required: false
      namespace:
        description: Registry namespace or project
        required: false
      tag:
        description: Image tag to use
        required: false
      push:
        description: Push images to registry
        required: true
        type: boolean
        default: false
      enable_notary:
        description: Include Notary
        required: true
        type: boolean
        default: true
      enable_trivy:
        description: Include Trivy
        required: true
        type: boolean
        default: true
      enable_charts:
        description: Include ChartMuseum
        required: true
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          install: true
      - name: Login to registry
        if: ${{ inputs.push && inputs.registry != '' && inputs.namespace != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build
        env:
          HARBOR_VERSION: ${{ inputs.harbor_version }}
          REGISTRY: ${{ inputs.registry }}
          NAMESPACE: ${{ inputs.namespace }}
          TAG: ${{ inputs.tag }}
          ENABLE_NOTARY: ${{ inputs.enable_notary }}
          ENABLE_TRIVY: ${{ inputs.enable_trivy }}
          ENABLE_CHARTS: ${{ inputs.enable_charts }}
          PUSH: ${{ inputs.push }}
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          chmod +x harbor-arm64-build/scripts/build-arm64.sh
          harbor-arm64-build/scripts/build-arm64.sh

